// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PowerATS.Infra.Data.Context;

#nullable disable

namespace PowerATS.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240123013900_Config-Inicial")]
    partial class ConfigInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PowerATS.Domain.Entities.Candidato", b =>
                {
                    b.Property<Guid>("IdCandidato")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdCandidato");

                    b.ToTable("Candidato", (string)null);
                });

            modelBuilder.Entity("PowerATS.Domain.Entities.CandidatoVaga", b =>
                {
                    b.Property<Guid>("IdCandidatoVaga")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCandidato")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdVaga")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdCandidatoVaga");

                    b.HasIndex("IdCandidato");

                    b.HasIndex("IdVaga");

                    b.ToTable("CandidatoVaga", (string)null);
                });

            modelBuilder.Entity("PowerATS.Domain.Entities.Curriculo", b =>
                {
                    b.Property<Guid>("IdCurriculo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurriculoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Curriculo");

                    b.Property<Guid>("IdCandidato")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdCurriculo");

                    b.HasIndex("IdCandidato");

                    b.ToTable("Curriculo", (string)null);
                });

            modelBuilder.Entity("PowerATS.Domain.Entities.Vaga", b =>
                {
                    b.Property<Guid>("IdVaga")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("TipoContratacao")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdVaga");

                    b.ToTable("Vaga", (string)null);
                });

            modelBuilder.Entity("PowerATS.Domain.Entities.CandidatoVaga", b =>
                {
                    b.HasOne("PowerATS.Domain.Entities.Candidato", "IdCandidatoNavigation")
                        .WithMany("CandidatoVagas")
                        .HasForeignKey("IdCandidato")
                        .IsRequired()
                        .HasConstraintName("FK_CandidatoVaga_Candidato");

                    b.HasOne("PowerATS.Domain.Entities.Vaga", "IdVagaNavigation")
                        .WithMany("CandidatoVagas")
                        .HasForeignKey("IdVaga")
                        .IsRequired()
                        .HasConstraintName("FK_CandidatoVaga_Vaga");

                    b.Navigation("IdCandidatoNavigation");

                    b.Navigation("IdVagaNavigation");
                });

            modelBuilder.Entity("PowerATS.Domain.Entities.Curriculo", b =>
                {
                    b.HasOne("PowerATS.Domain.Entities.Candidato", "IdCandidatoNavigation")
                        .WithMany("Curriculos")
                        .HasForeignKey("IdCandidato")
                        .IsRequired()
                        .HasConstraintName("FK_Curriculo_Candidato");

                    b.Navigation("IdCandidatoNavigation");
                });

            modelBuilder.Entity("PowerATS.Domain.Entities.Candidato", b =>
                {
                    b.Navigation("CandidatoVagas");

                    b.Navigation("Curriculos");
                });

            modelBuilder.Entity("PowerATS.Domain.Entities.Vaga", b =>
                {
                    b.Navigation("CandidatoVagas");
                });
#pragma warning restore 612, 618
        }
    }
}
