version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql-server-ats
    environment:
      SA_PASSWORD: 123@ats
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge